### PR TITLE
Fix task number

### LINKED ISSUE #58: Tests for Command classes
- [x] AddCommand
- [x] DeleteCommand
- [x] DoneCommand
- [x] EditCommand

### PR DESCRIPTION
**Pull request by daniellimws**
Currently, all commands still modify tasks based on their index in the array list instead of their assigned task number. This commit fixes this mistake. And change all instances of task index to task number because index sounds misleading.

Also made some minor changes to the formatting by removing redundant empty or new lines. And remove save.csv from our GitHub.

I also added tests for all the methods/classes involved to make sure they are all working as intended.

### CODE REVIEW

**Comment by daniellimws** [comment]
Also continuing the work in #59.

**Comment by daniellimws** [comment]
I merged #55 into this so that I can also catch exceptions. We can wait until that is merged before reviewing this if there are too many things.

File: src/main/java/athena/Athena.java [hunk 1]
```diff
@@ -1,46 +1,46 @@
...
-    private static Ui ui;
+    private Ui ui;
+    private Parser parser;
+    private Storage storage;
+    private TaskList taskList;
 
     public Athena() {
         ui = new Ui();
+        parser = new Parser();
+        storage = new Storage("save.csv", ui);
```
Comment (Kafcis) [inline src/main/java/athena/Athena.java]: the correct name here according to the user guide is load.csv. This was my mistake, eventually we should allow the user to change what file they are loading

File: src/main/java/athena/Storage.java [hunk 2]
```diff
@@ -40,7 +42,7 @@ public void saveTaskListData(TaskList tasks) {
     public TaskList loadTaskListData() {
         File csvFile = new File(filePath);
         TaskList output = new TaskList();
-        int maxIndex = -1;
+        int maxNumber = 0;
```
Comment (Kafcis) [inline src/main/java/athena/Storage.java:45]: There is a possibility of an empty save file, should initialise maxNumber to the default of -1?

File: src/main/java/athena/TaskList.java [hunk 3]
```diff
@@ -96,45 +79,37 @@ public void addTask(String name, String startTime, String duration,
...
-                taskToDelete = tasks.get(taskNumber);
-                index = counter;
-            }
-        }
-        tasks.remove(index);
-        return taskToDelete;
+    public Task deleteTask(int taskNumber) throws TaskNotFoundException {
+        Task task = getTaskFromNumber(taskNumber);
+        tasks.remove(task);
+        return task;
```
Comment (Kafcis) [inline src/main/java/athena/TaskList.java:106]: Much cleaner code than the original

File: src/main/java/athena/commands/EditCommand.java [hunk 4]
```diff
@@ -14,9 +15,9 @@
     private Importance taskImportance;
     private String taskNotes;
 
-    public EditCommand(int index, String name, String startTime, String duration, String deadline,
+    public EditCommand(int number, String name, String startTime, String duration, String deadline,
```
Comment (Kafcis) [inline src/main/java/athena/commands/EditCommand.java:20]: found it a bit weird that the argument order is not the same as add task, I know that the number is a required argument so its in the front, but it might look a bit messy to others.

I would have done the same, but am also not too sure about the correctness

**Review by Kafcis — COMMENTED** [review]
Should have separated the fixing of the task number and the test code, other than that looks great

File: src/main/java/athena/Storage.java (hunk 2 above)
Comment (daniellimws) [reply src/main/java/athena/Storage.java:45]: Actually I wasn't sure should the number start from 0 or 1. I thought our first task would start from 1?

File: src/main/java/athena/Athena.java (hunk 1 above)
Comment (daniellimws) [reply src/main/java/athena/Athena.java]: This was taken from #55. Can you comment over there?

File: src/main/java/athena/commands/EditCommand.java (hunk 4 above)
Comment (daniellimws) [reply src/main/java/athena/commands/EditCommand.java:20]: How about moving `number` to the first argument for `addTask` as well?

**Comment by daniellimws** [comment]
I think each change in the code should be accompanied with the test code so that we can merge with confidence that it works as intended.

File: src/main/java/athena/Athena.java (hunk 1 above)
Comment (Kafcis) [reply src/main/java/athena/Athena.java]: Done

File: src/main/java/athena/commands/EditCommand.java (hunk 4 above)
Comment (Kafcis) [reply src/main/java/athena/commands/EditCommand.java:20]: Sounds good!

File: src/main/java/athena/Storage.java (hunk 2 above)
Comment (Kafcis) [reply src/main/java/athena/Storage.java:45]: The TaskList initialises the maxNumber as -1. We can either change it here or there as long as its standardised. I suggest changing it here because I used this in some of the test code and allows us to check fo rpotentially unused TaskLists

**Comment by Kafcis** [comment]
That sounds logical, I will do that as well for the subsequent PRs too

File: src/test/java/athena/commands/EditCommandTest.java [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+    }
+
+    /**
+     * Asserts the task with the specified number can be successfully edited.
+     *
+     * @param taskNumber          Task number of the task to edit.
+     * @param taskList            TaskList to edit.
+     * @param taskListWithoutTask Reference taskList to compare with after deleting the task.
+     */
+    private void assertEditingSuccessful(int taskNumber, TaskList taskList, TaskList taskListWithoutTask)
```
Comment (amanda-chua) [inline src/test/java/athena/commands/EditCommandTest.java]: I think `taskListWithoutTask` should be `editedTaskList`

File: src/test/java/athena/commands/DoneCommandTest.java [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+    }
+
+    /**
+     * Asserts the task with the specified number can be successfully marked as done.
+     *
+     * @param taskNumber          Task number of the task to mark as done.
+     * @param taskList            TaskList to modify.
+     * @param taskListWithoutTask Reference taskList to compare with after marking the task as done.
+     */
+    private void assertDoneSuccessful(int taskNumber, TaskList taskList, TaskList taskListWithoutTask)
```
Comment (amanda-chua) [inline src/test/java/athena/commands/DoneCommandTest.java:122]: I think `taskListWithoutTask` should be `taskListWithDone`

**Review by amanda-chua — CHANGES_REQUESTED** [review]
Overall looks good

File: src/test/java/athena/commands/EditCommandTest.java (hunk 5 above)
Comment (daniellimws) [reply src/test/java/athena/commands/EditCommandTest.java]: Oops thanks for noticing

File: src/test/java/athena/commands/DoneCommandTest.java (hunk 6 above)
Comment (daniellimws) [reply src/test/java/athena/commands/DoneCommandTest.java:122]: Oops thanks for noticing

**Review by amanda-chua — APPROVED** [review]
Looks good

File: src/test/java/athena/commands/DoneCommandTest.java [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
```
Comment (amanda-chua) [inline src/test/java/athena/commands/DoneCommandTest.java:122]: Change `taskListWithoutTask` to `taskListWithDone`

**Review by amanda-chua — APPROVED** [review]
Looks good
