### PR TITLE
Error message when task is already done

### LINKED ISSUE #222: [PE-D] No exception when marking a task that is already done as done
As shown in the screenshot above, I has tried to mark a task named "name" done several times, and it seems that I am allowed to mark an already-done task as done. You may consider add an exception to refrain the users from mark done something already done as done.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: max-wunan/ped#4

### PR DESCRIPTION
**Pull request by wish2023**

### CODE REVIEW

File: src/main/java/athena/Storage.java [hunk 1]
```diff
@@ -114,6 +115,8 @@ public TaskList loadTaskListData() throws StorageException {
                 throw new StorageLoadFailException();
             } catch (TaskDuringSleepTimeException e) {
                 throw new StorageCorruptedException(data);
+            } catch (TaskIsDoneException e) {
+                throw new StorageCorruptedException(data);
```
Comment (daniellimws) [inline src/main/java/athena/Storage.java:120]: Hmm why would this place throw this exception?

**Review by daniellimws — APPROVED** [review]
Looks good. But we should check why does `Storage` throw this exception? So that we don't get any weird crashes during program startup.

File: src/main/java/athena/Storage.java (hunk 1 above)
Comment (wish2023) [reply src/main/java/athena/Storage.java:120]: Because line 104 uses `markTaskAsDone()` so I need to catch this exception otherwise there'll be error

Comment (daniellimws) [reply src/main/java/athena/Storage.java:120]: Ohh ok. I feel that we should have something like an `assert(false)` here because if the program does reach this line, it means we have done something wrong, since by right `TaskIsDoneException` shouldnt happen when loading from storage. But not really a big deal.

Comment (wish2023) [reply src/main/java/athena/Storage.java:120]: Okay I've made the change
